"""Protocol error codes (spec §6.1) plus local-only codes (spec §7)."""

from __future__ import annotations

ERROR_CODES = {
    # Registry / transport codes
    "BAD_REQUEST", "SCHEMA_INVALID", "VERSION_UNSUPPORTED", "METHOD_UNKNOWN",
    "ID_MISMATCH", "UNAUTHENTICATED", "FORBIDDEN", "KEY_INACTIVE",
    "ROLE_MISMATCH", "NOT_FOUND", "HEAD_CONFLICT", "CUT_MISMATCH",
    "IDEMPOTENCY_CONFLICT", "STATEMENT_EXISTS", "ID_CONFLICT", "STATE_CONFLICT",
    "BODY_LIMIT", "BUNDLE_LIMIT", "GRAPH_LIMIT", "CONTENT_TYPE",
    "CONTENT_ENCODING", "HASH_MISMATCH", "SIGNATURE_INVALID", "PARENT_MISSING",
    "PARENT_MISMATCH", "PARENT_INACTIVE", "DESCRIPTOR_MISMATCH",
    "STATEMENT_INVALID", "COMMAND_EXPIRED", "CLOCK_AHEAD", "RATE_LIMIT",
    "STORAGE_UNAVAILABLE", "AUDIT_KEY_UNAVAILABLE", "CAPACITY_LIMIT",
    # Verification-only reasons usable as failure codes
    "UNTRUSTED_GENESIS", "CHAIN_MISMATCH", "AUDIT_BINDING_MISMATCH",
    "MINIMUM_HEAD_MISMATCH", "RETRACTED_ANCESTOR", "REVOKED_ANCESTOR",
    "DENIED_KEY", "MISSING_TRAINING", "ARTIFACT_MISMATCH", "STALE_HEAD",
    "TARGET_MISSING",
    # Local-only codes
    "USAGE", "CONFIG_INVALID", "KEY_PERMISSIONS", "KEY_ERROR", "NETWORK_ERROR",
    "OUTPUT_EXISTS", "ARTIFACT_CHANGED", "IO_ERROR", "INTERRUPTED",
}

HTTP_STATUS = {
    "BAD_REQUEST": 400, "SCHEMA_INVALID": 400, "VERSION_UNSUPPORTED": 400,
    "METHOD_UNKNOWN": 400, "ID_MISMATCH": 400, "UNAUTHENTICATED": 401,
    "FORBIDDEN": 403, "KEY_INACTIVE": 403, "ROLE_MISMATCH": 403,
    "NOT_FOUND": 404, "HEAD_CONFLICT": 409, "CUT_MISMATCH": 409,
    "IDEMPOTENCY_CONFLICT": 409, "STATEMENT_EXISTS": 409, "ID_CONFLICT": 409,
    "STATE_CONFLICT": 409, "BODY_LIMIT": 413, "BUNDLE_LIMIT": 413,
    "GRAPH_LIMIT": 413, "CONTENT_TYPE": 415, "CONTENT_ENCODING": 415,
    "HASH_MISMATCH": 422, "SIGNATURE_INVALID": 422, "PARENT_MISSING": 422,
    "PARENT_MISMATCH": 422, "PARENT_INACTIVE": 422, "DESCRIPTOR_MISMATCH": 422,
    "STATEMENT_INVALID": 422, "COMMAND_EXPIRED": 422, "CLOCK_AHEAD": 422,
    "RATE_LIMIT": 429, "STORAGE_UNAVAILABLE": 503, "AUDIT_KEY_UNAVAILABLE": 503,
    "CAPACITY_LIMIT": 503,
}

RETRYABLE = {
    "RATE_LIMIT", "STORAGE_UNAVAILABLE", "AUDIT_KEY_UNAVAILABLE",
    "CAPACITY_LIMIT", "NETWORK_ERROR",
}


class SunlightError(Exception):
    """Error carrying a protocol ErrorBody; never leaks upstream text."""

    def __init__(self, code: str, head=None, cause=None):
        if code not in ERROR_CODES:
            code = "IO_ERROR"
        super().__init__(code)
        self.code = code
        self.body = {
            "code": code,
            "retryable": code in RETRYABLE,
            "head": head,
        }
        self.__cause__ = cause


def error_body(e):
    if isinstance(e, SunlightError):
        return e.body
    return {"code": "IO_ERROR", "retryable": False, "head": None}


_CLI_EXIT = {
    "USAGE": 2, "CONFIG_INVALID": 2, "BAD_REQUEST": 2, "SCHEMA_INVALID": 2,
    "VERSION_UNSUPPORTED": 2, "STATEMENT_INVALID": 2, "CONTENT_TYPE": 2,
    "CONTENT_ENCODING": 2, "METHOD_UNKNOWN": 2, "ID_MISMATCH": 2,
    "CLOCK_AHEAD": 2,
    "HASH_MISMATCH": 3, "SIGNATURE_INVALID": 3, "PARENT_MISSING": 3,
    "PARENT_MISMATCH": 3, "PARENT_INACTIVE": 3, "DESCRIPTOR_MISMATCH": 3,
    "CHAIN_MISMATCH": 3, "AUDIT_BINDING_MISMATCH": 3, "ARTIFACT_MISMATCH": 3,
    "NOT_FOUND": 4, "TARGET_MISSING": 4, "UNTRUSTED_GENESIS": 4,
    "MINIMUM_HEAD_MISMATCH": 4, "RETRACTED_ANCESTOR": 4, "REVOKED_ANCESTOR": 4,
    "DENIED_KEY": 4, "MISSING_TRAINING": 4, "STALE_HEAD": 4,
    "UNAUTHENTICATED": 5, "FORBIDDEN": 5, "ROLE_MISMATCH": 5,
    "KEY_INACTIVE": 5, "KEY_PERMISSIONS": 5, "KEY_ERROR": 5,
    "RATE_LIMIT": 6, "STORAGE_UNAVAILABLE": 6, "AUDIT_KEY_UNAVAILABLE": 6,
    "CAPACITY_LIMIT": 6, "NETWORK_ERROR": 6,
    "HEAD_CONFLICT": 7, "CUT_MISMATCH": 7, "IDEMPOTENCY_CONFLICT": 7,
    "ID_CONFLICT": 7, "STATEMENT_EXISTS": 7, "STATE_CONFLICT": 7,
    "COMMAND_EXPIRED": 7,
    "BODY_LIMIT": 8, "BUNDLE_LIMIT": 8, "GRAPH_LIMIT": 8, "OUTPUT_EXISTS": 8,
    "ARTIFACT_CHANGED": 8, "IO_ERROR": 8,
    "INTERRUPTED": 130,
}


def cli_exit_for(code: str) -> int:
    return _CLI_EXIT.get(code, 1)
