/**
 * Cross-runtime golden check: the TypeScript fixtures module must produce
 * byte-identical objects to tests/fixtures.json, which was generated by the
 * independent Python port of spec §6.2 (tools/gen_fixtures.py).  This is the
 * "independently generated fixtures" gate — known-answer verification, not a
 * self-generated oracle.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as F from "../src/fixtures.js";
import { verify } from "../src/verify.js";
import { manifestArtifact } from "../src/artifact.js";
import { parseTreeManifest } from "../src/schema.js";

const here = dirname(fileURLToPath(import.meta.url));
const fx = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));

test("genesis, keys, ids match generated fixtures", () => {
  assert.deepEqual(F.G, fx.genesis);
  assert.equal(F.L, fx.ledger);
  assert.equal(F.T, fx.now_ms);
  assert.equal(F.NONCE, fx.nonce_hex);
  assert.equal(F.H0.hash, fx.genesis_hash);
  assert.deepEqual(F.H0, fx.H0);
  assert.deepEqual(F.KA.key, fx.keys.KA);
  assert.deepEqual(F.KL.key, fx.keys.KL);
  assert.deepEqual(F.KP.key, fx.keys.KP);
  assert.deepEqual(F.KN.key, fx.keys.KN);
});

test("artifacts match generated fixtures", () => {
  assert.deepEqual(F.A, fx.artifacts.A);
  assert.deepEqual(F.Z, fx.artifacts.Z);
  assert.deepEqual(F.M, fx.artifacts.M);
});

test("tree manifest is deterministic and matches generated fixture", () => {
  assert.deepEqual(F.ENTRIES.length, 8);
  const tm = parseTreeManifest({
    v: "sunlight.tree/1",
    files: [
      { path: "b.txt", digest: F.Z.digest, bytes: 0 },
      { path: "a.txt", digest: F.A.digest, bytes: 3 },
    ].sort((x, y) => (x.path < y.path ? -1 : 1)),
  });
  assert.deepEqual(tm, fx.tree_manifest);
  assert.deepEqual(manifestArtifact(tm), fx.tree_artifact);
});

test("statements S1..S4 and vector statements match", () => {
  assert.deepEqual(F.S1, fx.statements.S1);
  assert.deepEqual(F.S2, fx.statements.S2);
  assert.deepEqual(F.S3, fx.statements.S3);
  assert.deepEqual(F.S4, fx.statements.S4);
});

test("commands C1..C8 and entries E1..E8 match", () => {
  const cmds = [F.C1, F.C2, F.C3, F.C4, F.C5, F.C6, F.C7, F.C8];
  for (let i = 0; i < 8; i++) {
    assert.deepEqual(cmds[i], fx.commands[`C${i + 1}`], `C${i + 1}`);
  }
  const ents = [F.E1, F.E2, F.E3, F.E4, F.E5, F.E6, F.E7, F.E8];
  for (let i = 0; i < 8; i++) {
    assert.deepEqual(ents[i], fx.entries[`E${i + 1}`], `E${i + 1}`);
    assert.deepEqual(F.ref(ents[i]!), fx.heads[`H${i + 1}`], `H${i + 1}`);
  }
});

test("bundles, trust, observation, freshness, V4 match", () => {
  assert.deepEqual(F.F4, fx.bundles.F4);
  assert.deepEqual(F.F7, fx.bundles.F7);
  assert.deepEqual(F.F8, fx.bundles.F8);
  assert.deepEqual(F.TRUST, fx.trust);
  assert.deepEqual(F.OBS4, fx.obs4);
  assert.deepEqual(F.FRESH4, fx.fresh4);
  assert.deepEqual(F.head(F.H4, F.NONCE), fx.heads_signed.H4_nonce);
  assert.deepEqual(F.head(F.H4), fx.heads_signed.H4_plain);
});

test("verify(F4) returns the exact generated V4", () => {
  const v = verify({ bundle: F.F4, trust: F.TRUST, observation: null, freshness: null });
  assert.deepEqual(v, fx.verification_v4);
  assert.deepEqual(v, F.V4);
});

test("client/deploy config fixtures match constants", () => {
  assert.deepEqual(F.CLIENT_CONFIG, fx.client_config);
  assert.deepEqual(F.DEPLOY_CONFIG, fx.deploy_config);
});
